#!/bin/bash

die(){ echo "$*" >&2; exit 1; }

BACKUP="$0"

BACKUP_CONF="${BACKUP_CONF:-default}"

if [ -r "$HOME/.config/backup/${BACKUP_CONF}.env" ]; then
	CONFIG_BASE="$HOME/.config/backup"
elif [ -r "/etc/backup/${BACKUP_CONF}.env" ]; then
	CONFIG_BASE="/etc/backup"
else
	die "Configuration '${BACKUP_CONF}' does not exist."
fi

if [ -e "${CONFIG_BASE}/${BACKUP_CONF}.exclude" ]; then
	EXCLUDE_FILE="${CONFIG_BASE}/${BACKUP_CONF}.exclude"
fi

. "${CONFIG_BASE}/${BACKUP_CONF}.env" || die "Could not read envfile."

command -v $CMD_BORG &>/dev/null \
        || die 'Cannot find borg executable! Verify the CMD_BORG variable.'

case "$1" in

	do-create)
		$CMD_BORG create \
			-x \
			${OPT_BORG} ${OPT_BORG_CREATE} \
			${EXCLUDE_FILE:+--exclude-from=${EXCLUDE_FILE}} \
			--exclude-if-present .nobackup \
			::'{hostname}'${SUFFIX}'-{now:%Y-%m-%dT%H:%M:%S}' \
			${SOURCES[@]:-/}
		;;

	do-prune)
		$CMD_BORG prune \
			${OPT_BORG} ${OPT_BORG_PRUNE} \
			--prefix='{hostname}'${SUFFIX} \
			${KEEP_WITHIN:+--keep-within=${KEEP_WITHIN}} \
			${KEEP_HOURLY:+--keep-hourly=${KEEP_HOURLY}} \
			${KEEP_DAILY:+--keep-daily=${KEEP_DAILY}} \
			${KEEP_WEEKLY:+--keep-weekly=${KEEP_WEEKLY}} \
			${KEEP_MONTHLY:+--keep-monthly=${KEEP_MONTHLY}} \
			${KEEP_YEARLY:+--keep-yearly=${KEEP_YEARLY}} \
			${KEEP_LAST:+--keep-last=${KEEP_LAST}}
		;;

	run|"")
		"${BACKUP}" do-create \
		|| die "borg failed to create archive."
		"${BACKUP}" do-prune \
		|| die "borg failed to prune archives"
		;;
	*)
		borg ${OPT_BORG} $*
		;;
esac
