#!/bin/bash

die(){ echo "$*" >&2; exit 1; }

command -v borg &>/dev/null \
	|| die 'Cannot find borg executable!'

BACKUP_CONF="${BACKUP_CONF:-default}"

if [ -r "$HOME/.config/backup/${BACKUP_CONF}.env" ]; then
	CONFIG_BASE="$HOME/.config/backup"
elif [ -r "/etc/backup/${BACKUP_CONF}.env" ]; then
	CONFIG_BASE="/etc/backup"
else
	die "Configuration '${BACKUP_CONF}' does not exist."
fi

if [ -e "${CONFIG_BASE}/${BACKUP_CONF}.exclude" ]; then
	EXCLUDE_FILE="${CONFIG_BASE}/${BACKUP_CONF}.exclude"
fi

. "${CONFIG_BASE}/${BACKUP_CONF}.env" || die "Could not read envfile."

case "$1" in
	run|"")
		borg prune \
			${OPT_BORG} ${OPT_BORG_PRUNE} \
			--prefix='{hostname}'${SUFFIX} \
			${KEEP_WITHIN:+--keep-within=${KEEP_WITHIN}} \
			${KEEP_DAILY:+--keep-daily=${KEEP_DAILY}} \
			${KEEP_WEEKLY:+--keep-weekly=${KEEP_WEEKLY}} \
			${KEEP_MONTHLY:+--keep-monthly=${KEEP_MONTHLY}} \
			${KEEP_YEARLY:+--keep-yearly=${KEEP_YEARLY}} \
		|| die "borg failed to prune archives"

		borg create \
			-x \
			${OPT_BORG} ${OPT_BORG_CREATE} \
			${EXCLUDE_FILE:+--exclude-from=${EXCLUDE_FILE}} \
			::'{hostname}'${SUFFIX}'-{now:%Y-%m-%d_%H:%M}' \
			${SOURCES[@]:-/} \
		|| die "borg failed to create archive."
		;;
	*)
		borg ${OPT_BORG} $*
		;;
esac
